[profile.default]
src = "src"
out = "out"
ffi = true
ast = true
build_info = true
optimizer = true
optimizer_runs = 200
var_ir = true
extra_output = ["storageLayout"]
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
