name: AI Auto-Fix

on:
  workflow_run:
    workflows:
      - Lint App
      - Lint Contracts
      - Auto Prerelease
      - Deploy App
      - Deploy Contract
      - Deploy Wiki
      - AI Document
      - AI Review
      - AI Triage
    types: [completed]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-fix:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      FAILED_WORKFLOW_NAME: ${{ github.event.workflow_run.name }}
      FAILED_RUN_URL: ${{ github.event.workflow_run.html_url }}
    steps:
      - name: Check OpenAI configuration
        id: ai-inputs
        run: |
          if [ -z "$OPENAI_API_KEY" ]; then
            echo "::warning::OPENAI_API_KEY secret is not configured. Skipping auto-fix." >&2
            echo "enabled=false" >> "$GITHUB_OUTPUT"
          else
            echo "enabled=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Checkout Failing Ref
        if: steps.ai-inputs.outputs.enabled == 'true'
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
          fetch-depth: 0

      - name: Setup Bun
        if: steps.ai-inputs.outputs.enabled == 'true'
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        if: steps.ai-inputs.outputs.enabled == 'true'
        run: bun install --frozen-lockfile

      - name: Run OpenAI Autofix
        if: steps.ai-inputs.outputs.enabled == 'true'
        uses: openai/codex-action@v1
        id: codex
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          prompt: >-
            You are working in a Bun + TypeScript monorepo with Foundry contracts and GitHub Actions.
            Read the repository, run the Bun lint and build scripts as well as `forge test`,
            identify the minimal change needed to make these commands succeed, implement only that change, and stop.
            Do not refactor unrelated code or files. Keep changes small and surgical.
          codex_args: '["--config","sandbox_mode=\"workspace-write\"","--config","allow_network=\"false\""]'

      - name: Setup Foundry
        if: steps.ai-inputs.outputs.enabled == 'true'
        uses: foundry-rs/foundry-toolchain@v1

      - name: Verify lint
        if: steps.ai-inputs.outputs.enabled == 'true'
        run: bun run lint

      - name: Verify build
        if: steps.ai-inputs.outputs.enabled == 'true'
        env:
          VITE_PUBLIC_APP_ID: test-app
          VITE_PUBLIC_CONTRACT_ADDRESS: 0x0000000000000000000000000000000000000000
        run: bun run build

      - name: Install Foundry dependencies
        working-directory: contracts
        if: steps.ai-inputs.outputs.enabled == 'true'
        run: forge install

      - name: Verify contracts
        working-directory: contracts
        if: steps.ai-inputs.outputs.enabled == 'true'
        run: forge test --silent

      - name: Create pull request with fixes
        if: steps.ai-inputs.outputs.enabled == 'true' && success()
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "fix(ci): auto-fix failing tests via AI assistant"
          branch: ai/autofix-${{ github.event.workflow_run.run_id }}
          base: ${{ github.event.workflow_run.head_branch }}
          title: "Auto-fix failing CI via AI assistant"
          body: |
            This pull request was generated automatically in response to a CI failure on workflow `${{ env.FAILED_WORKFLOW_NAME }}`.
            Failed run: ${{ env.FAILED_RUN_URL }}
            Head branch: `${{ github.event.workflow_run.head_branch }}`
            The changes aim to be the minimal set required to restore a green build.
            Changes were generated with the OpenAI Codex GitHub Action.
