name: Auto Prerelease

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  prerelease:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Determine tag name
        id: tag
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          DATE=$(date -u +"%Y%m%d")
          TAG="pre-${DATE}-${SHORT_SHA}"
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"

      - name: Create or update pre-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ steps.tag.outputs.tag }}
        run: |
          set -euo pipefail

          NAME="Pre-release ${TAG}"
          NOTES="Automated pre-release for commit ${GITHUB_SHA}."

          if gh release view "$TAG" >/dev/null 2>&1; then
            gh release edit "$TAG" \
              --title "$NAME" \
              --notes "$NOTES" \
              --prerelease \
              --target "$GITHUB_SHA"
          else
            gh release create "$TAG" \
              --title "$NAME" \
              --notes "$NOTES" \
              --prerelease \
              --target "$GITHUB_SHA"
          fi
