name: Codex Document

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * 1"

permissions:
  contents: write
  pull-requests: write

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    concurrency:
      group: codex-document
      cancel-in-progress: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Ensure docs directory exists
        run: mkdir -p docs

      - name: Run Codex documentation pass
        id: codex
        uses: openai/codex-action@v1
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          prompt: >-
            You are the documentation maintainer for the Civilisation DApp repository.
            Review the existing content under the docs/ directory and the README.
            Identify missing or unclear documentation topics and add or improve Markdown files under docs/ to cover them.
            Keep all documentation in English, focus on accuracy, and do not modify source code outside of docs/ or README.md.
            When updating files, include navigation links where helpful.
          codex_args: '["--config","sandbox_mode=\"workspace-write\"","--config","allow_network=\"false\""]'

      - name: Detect changes
        id: changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          else
            echo "changed=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Create documentation pull request
        if: steps.changes.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "docs: refresh documentation via Codex"
          branch: codex/documentation-${{ github.run_id }}
          title: "Update documentation via Codex"
          body: |
            Automated documentation refresh generated by Codex.
            This PR adds or updates Markdown files under `docs/` to keep the wiki in sync.
          add-paths: |
            docs/**
            README.md

      - name: No documentation changes detected
        if: steps.changes.outputs.changed == 'false'
        run: echo "Codex did not propose any documentation updates."
