name: Deploy App and Contracts

on:
  push:
    branches: ['main']
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  deployments: write

concurrency:
  group: 'deploy-app-and-contracts'
  cancel-in-progress: false

jobs:
  build-app:
    runs-on: ubuntu-latest
    environment: testnet

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Setup Bun.js
        uses: oven-sh/setup-bun@v2

      - name: Install Dependencies
        run: bun install

      - name: Build App
        env:
          VITE_PUBLIC_APP_ID: ${{ vars.WORLD_APP_ID }}
          VITE_PUBLIC_CONTRACT_ADDRESS: ${{ vars.WORLD_CONTRACT_ADDRESS }}
        run: bun run build

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./dist

  deploy-contracts:
    runs-on: ubuntu-latest
    environment: testnet
    needs: build-app

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Setup Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install Dependencies
        working-directory: contracts
        run: |
          forge install worldcoin/world-id-contracts
          forge install foundry-rs/forge-std
          forge build

      - name: Deploy Contracts
        working-directory: contracts
        env:
          PRIVATE_KEY: ${{ secrets.WORLDCHAIN_WALLET_PRIVATE_KEY }}
          RPC_URL: ${{ vars.WORLDCHAIN_RPC_URL }}
        run: |
          set -euo pipefail

          for file in $(ls script/*.s.sol | sort); do
            raw=$(basename "$file" .s.sol)
            base=$(echo "$raw" | sed -E 's/^[0-9]+_//')

            echo ">>> Running forge script for $file (contract: $base)"
            forge script "$file:$base" \
              --rpc-url "$RPC_URL" \
              --private-key "$PRIVATE_KEY" \
              --broadcast \
              -vvvv
          done

      - name: Extract Diamond Address
        id: extract
        working-directory: contracts
        run: |
          FILE="broadcast/00_Deploy.s.sol/${{ vars.CHAIN_ID }}/run-latest.json"
          test -f "$FILE" || { echo "Broadcast file not found: $FILE"; exit 1; }

          DIAMOND=$(jq -r '.transactions[] | select(.transactionType=="CREATE" and .contractName=="Diamond") | .contractAddress' "$FILE" | head -n1)

          if [ -z "$DIAMOND" ] || [ "$DIAMOND" = "null" ]; then
            echo "❌ Could not extract Diamond address"
            exit 1
          fi

          echo "Diamond address: $DIAMOND"
          echo "diamond_address=$DIAMOND" >> "$GITHUB_OUTPUT"

      - name: Save Diamond Address as GitHub Environment variable
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          ENVIRONMENT: testnet
          DIAMOND_ADDR: ${{ steps.extract.outputs.diamond_address }}
        run: |
          set -e
          if gh api \
            --method GET \
            -H "Accept: application/vnd.github+json" \
            "/repos/${GITHUB_REPOSITORY}/environments/${ENVIRONMENT}/variables/APP_CONTRACT_ADDRESS" \
            >/dev/null 2>&1; then
            gh api \
              --method PATCH \
              -H "Accept: application/vnd.github+json" \
              -f value="$DIAMOND_ADDR" \
              "/repos/${GITHUB_REPOSITORY}/environments/${ENVIRONMENT}/variables/APP_CONTRACT_ADDRESS"
          else
            gh api \
              --method POST \
              -H "Accept: application/vnd.github+json" \
              -f name="APP_CONTRACT_ADDRESS" \
              -f value="$DIAMOND_ADDR" \
              "/repos/${GITHUB_REPOSITORY}/environments/${ENVIRONMENT}/variables"
          fi
          echo "✅ Saved APP_CONTRACT_ADDRESS=$DIAMOND_ADDR to environment '$ENVIRONMENT'"

      - name: Collect all ABIs
        working-directory: contracts
        run: |
          mkdir -p /tmp/abi
          rsync -avR \
            --include '*/' \
            --include '*.json' \
            --exclude '*' \
            ./out/ ./broadcast/ /tmp/abi/

      - name: Upload ABIs as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Diamond-ABIs
          path: /tmp/abi/
