name: Lint App and Contracts

on:
  push:
    branches: [main]
    paths:
      - "src/**"
      - "vite.config.*"
      - "eslint.config.*"
      - "package.json"
      - "bun.lockb"
      - "contracts/**"
      - ".solhint.json"
      - ".prettier*"
  pull_request:
    paths:
      - "src/**"
      - "vite.config.*"
      - "eslint.config.*"
      - "package.json"
      - "bun.lockb"
      - "contracts/**"
      - ".solhint.json"
      - ".prettier*"
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Setup Bun.js
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - name: Run Lint Suite
        run: bun run lint
