name: Lint Contracts

on:
  push:
    paths:
      - "contracts/**"
      - "package.json"
      - "bun.lock"
      - ".solhint.json"
  pull_request:
    paths:
      - "contracts/**"
      - "package.json"
      - "bun.lock"
      - ".solhint.json"
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Setup Bun.js
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - name: Run Solhint
        run: bun run lint:sol
