name: Lint App

on:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'vite.config.*'
      - 'eslint.config.*'
      - 'package.json'
      - 'bun.lockb'
      - '.github/workflows/lint-app.yml'
  pull_request:
    paths:
      - 'src/**'
      - 'vite.config.*'
      - 'eslint.config.*'
      - 'package.json'
      - 'bun.lockb'
      - '.github/workflows/lint-app.yml'

jobs:
  lint-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run ESLint
        run: bun run lint:ts -- --format github -
