name: Lint Contracts

on:
  push:
    branches: [main]
    paths:
      - 'contracts/**'
      - '.solhint.json'
      - '.prettierrc*'
      - '.github/workflows/lint-contracts.yml'
  pull_request:
    paths:
      - 'contracts/**'
      - '.solhint.json'
      - '.prettierrc*'
      - '.github/workflows/lint-contracts.yml'

jobs:
  lint-contracts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run ESLint
        run: bun run lint:contracts -- --format sarif --output-file eslint-results.sarif

      - name: Upload ESLint results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: eslint-results.sarif
