name: Test Web App

on:
  push:
    branches: [main]
    paths:
      - "src/**"
      - "package.json"
      - "bun.lock"
      - "bun.lockb"
      - "vite.config.*"
      - "tsconfig*.json"
      - ".github/workflows/test-app.yml"
  pull_request:
    paths:
      - "src/**"
      - "package.json"
      - "bun.lock"
      - "bun.lockb"
      - "vite.config.*"
      - "tsconfig*.json"
      - ".github/workflows/test-app.yml"
  workflow_dispatch:

jobs:
  test-web:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Bun.js
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - name: Run Web Tests
        run: bun run test:web
